export const BANKS = [
  'Banco de Chile',
  'Banco Santander',
  'BCI',
  'Scotiabank Chile',
  'Banco Estado',
  'BICE',
  'Itaú Chile',
  'Banco Security',
  'Banco Falabella',
  'Banco Ripley',
  'Banco Consorcio',
  'Banco Internacional',
  'Banco BTG Pactual',
  'HSBC Bank Chile',
  'Tenpo',
  'MACH',
  'Mercado Pago',
];
